<h3>Login</h3>
<hr>
<?php
//if ($this->error):
//    var_dump($this->error);
//endif;
$form = $this->form;
$form->setAttribute('action', $this->url('sonuser-auth'));
$form->prepare();
?>
<div class="col-xs-6">
    <div class="well">
        <?= $this->form()->openTag($form); ?>
        <div class="form-group">
            <label for="email" class="control-label">Usuário</label>
            <input type="text" class="form-control" id="email" name="email" value="" required="" title="Por favor, insira seu e-mail" placeholder="exemplo@gmail.com">
            <span class="help-block"></span>
        </div>
        <div class="form-group">
            <label for="password" class="control-label">Senha</label>
            <input type="password" class="form-control" id="password" name="password" value="" required="" title="Por favor, insira sua senha" placeholder="Por favor, insira sua senha">
            <span class="help-block"></span>
        </div>

        <div class="alert alert-danger <?= ($this->error) ? "" : "hide" ?>" role="alert">
            <i class="glyphicon glyphicon-remove"></i> <b>Usuário</b> ou <b>Senha</b> inválidos !
        </div>

        <div class="checkbox">
            <label>
                <input type="checkbox" name="remember" id="remember"> Remember login
            </label>
            <p class="help-block">(if this is a private computer)</p>
        </div>
        <button type="submit" class="btn btn-success btn-block">Login</button>
        <a href="/forgot/" class="btn btn-default btn-block">Help to login</a>
        <?= $this->form()->closeTag(); ?>
    </div>
</div>
<div class="col-xs-6">
    <p class="lead">Register now for <span class="text-success">FREE</span></p>
    <ul class="list-unstyled" style="line-height: 2">
        <li><span class="fa fa-check text-success"></span> See all your orders</li>
        <li><span class="fa fa-check text-success"></span> Fast re-order</li>
        <li><span class="fa fa-check text-success"></span> Save your favorites</li>
        <li><span class="fa fa-check text-success"></span> Fast checkout</li>
        <li><span class="fa fa-check text-success"></span> Get a gift <small>(only new customers)</small></li>
        <li><a href="/read-more/"><u>Read more</u></a></li>
    </ul>
    <p><a href="/new-customer/" class="btn btn-info btn-block">Yes please, register now!</a></p>
</div>